
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = [ ]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
[[constraint]]
  name = "github.com/opentracing/basictracer-go"
[[constraint]]
  name = "github.com/opentracing/opentracing-go"
[[constraint]]
  name = "github.com/rs/xid"
[[constraint]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
[[constraint]]
  name = "github.com/uber/jaeger-client-go"
[[constraint]]
  name = "github.com/sirupsen/logrus"
[[constraint]]
  name = "github.com/spf13/cobra"
